#+TITLE: KMonadX
#+begin_center
*An extension language for* ~kbd~: *the keyboard programming manager [[https://github.com/kmonad/kmonad][KMonad]]'s configuration language.*
#+end_center

* Introduction
KMonad is an incredibly powerful tool, but its configuration can be quite verbose, and the base language lacks several features which could drasticly reduce boilerplate.
Layer inheritance and declarative bindings (~i -> j~) are 2 of those features which could easily be built on top of the language; rather than attempting to modify the core language, potentially adding unnecessary complexity, creating a language that transpiled to ~kbd~ would be much simpler, much more maintainable and would allow for a lot more syntactic flexibility.
From this idea came ~kbdx~, a TOML-like language which aims to be expressive, readable and concise, and the ~kmonadx~ CLI tool for transpiling it to ~kbd~.
* Documentation
KMonadX has two sets of documentation: *Target* documentation and *Functional* documentation.
The *Target* documentation is an example configuration which contains all the functionality KMonadX hopes to implement, while the *Functional* documentation is an example configuration which contains the functionality KMonadX /currently/ has, meaning that it compiles correctly on ~HEAD~.

#+begin_center
| [[./functional_tutorial.kbdx][Functional Documentation]] | [[./target_tutorial.kbdx][Target Documentation]] |
#+end_center

To see the transpiled version of the functional documentation, see [[./compiled_functional_tutorial.kbd][compiled_functional_tutorial.kbd]]
* TODO Minimal Example
This section will show a very condensed version of the documentation that shows what KMonadX is capable of doing.
This /may/ be split into *Target* and *Functional* sections.
* TODO Installation
This section will give installation instructions, both from source and from GitHub releases.
* TODO Development
Go through branch naming, issues, pull requests, etc.
